# version matches debian trixie
FROM python:3.13-trixie

RUN mkdir -p /app
COPY . /app
WORKDIR /app

RUN pip install -r requirements_dev.txt

EXPOSE 8000


CMD python datatighub/manage.py runserver 0.0.0.0:8000
