# version matches debian bookwork
FROM python:3.11-bookworm

RUN mkdir -p /app
COPY . /app
WORKDIR /app

RUN pip install -r requirements_dev.txt

EXPOSE 8000


CMD python datatighub/manage.py runserver 0.0.0.0:8000
