# Generated by Django 5.0.7 on 2024-07-21 12:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datatighubcore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("url", models.CharField(unique=True)),
                (
                    "last_check_result",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("UNCLEAR", "Unclear"),
                            ("ROBOT_BLOCKED", "Robot blocked"),
                            ("FAILED", "Failed"),
                        ],
                        null=True,
                    ),
                ),
                ("last_check_final_url", models.CharField(null=True)),
                ("last_check_status_code", models.IntegerField(null=True)),
                ("last_check_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
