# Generated by Django 5.2.7 on 2026-01-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datatighubgithub", "0002_githubrepository_github_api_public_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubrepository",
            name="directory",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
