import environ

env = environ.Env(
    DATATIG_HUB_GITHUB_OAUTH_APP_CLIENT_ID=(str, ""),
    DATATIG_HUB_GITHUB_OAUTH_APP_CLIENT_SECRET=(str, ""),
)

SETTINGS = {
    "OAUTH_APP_CLIENT_ID": env("DATATIG_HUB_GITHUB_OAUTH_APP_CLIENT_ID"),
    "OAUTH_APP_CLIENT_SECRET": env("DATATIG_HUB_GITHUB_OAUTH_APP_CLIENT_SECRET"),
}
