from django.urls import path

from . import views

app_name = "datatighubgithub_repository"
urlpatterns = [
    path(
        "<org_or_user_name>/<repo_name>",
        views.GithubRepositoryView.as_view(),
        name="index",
    ),
    path(
        "<org_or_user_name>/<repo_name>/builds",
        views.GithubRepositoryBuildsView.as_view(),
        name="builds",
    ),
    path(
        "<org_or_user_name>/<repo_name>/webhook/<webhook_code>",
        views.GithubRepositorWebhookView.as_view(),
        name="webhook",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>",
        views.GithubRepositoryTreeView.as_view(),
        name="tree_index",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/api1.json",
        views.GithubRepositoryTreeViewAPI1.as_view(),
        name="tree_api1",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/errors",
        views.GithubRepositoryTreeErrorsView.as_view(),
        name="tree_errors",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/type/<type_id>",
        views.GithubRepositoryTreeTypeView.as_view(),
        name="tree_type_index",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/type/<type_id>/record",
        views.GithubRepositoryTreeTypeListRecordsView.as_view(),
        name="tree_type_list_records",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/type/<type_id>/record_api1.json",
        views.GithubRepositoryTreeTypeListRecordsAPI1View.as_view(),
        name="tree_type_list_records_api1",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/type/<type_id>/api1.json",
        views.GithubRepositoryTreeTypeAPI1View.as_view(),
        name="tree_type_api1",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/type/<type_id>/new_record",
        views.GithubRepositoryTreeTypeNewRecordView.as_view(),
        name="tree_type_new_record",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/type/<type_id>/new_record/submission/<submission_id>",
        views.GithubRepositoryTreeTypeNewRecordSubmissionView.as_view(),
        name="tree_type_new_record_submission",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/type/<type_id>/record/<record_id>",
        views.GithubRepositoryTreeTypeRecordView.as_view(),
        name="tree_type_record_index",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/type/<type_id>/record/<record_id>/api1.json",
        views.GithubRepositoryTreeTypeRecordAPI1View.as_view(),
        name="tree_type_record_api1",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/type/<type_id>/record/<record_id>/edit",
        views.GithubRepositoryTreeTypeRecordEditView.as_view(),
        name="tree_type_record_edit",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/type/<type_id>/"
        + "record/<record_id>/edit/submission/<submission_id>",
        views.GithubRepositoryTreeTypeRecordEditSubmissionView.as_view(),
        name="tree_type_record_edit_submission",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/type/<type_id>/field/<field_id>",
        views.GithubRepositoryTreeTypeFieldView.as_view(),
        name="tree_type_field_index",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/download/sqlite",
        views.GithubRepositoryTreeDownloadSQLiteView.as_view(),
        name="tree_download_sqlite_index",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/download/frictionless_csv_zip",
        views.GithubRepositoryTreeDownloadFrictionlessView.as_view(),
        name="tree_download_frictionless_index",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/calendar/<calendar_id>",
        views.GithubRepositoryTreeCalendarView.as_view(),
        name="tree_calendar_index",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/calendar/<calendar_id>/api1.json",
        views.GithubRepositoryTreeCalendarAPI1View.as_view(),
        name="tree_calendar_api1",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/calendar/<calendar_id>/fullcalendar.json",
        views.GithubRepositoryTreeCalendarFullCalendarDataView.as_view(),
        name="tree_calendar_fullcalendar_data",
    ),
    path(
        "<org_or_user_name>/<repo_name>/tree/<tree_name>/calendar/<calendar_id>/events.ical",
        views.GithubRepositoryTreeCalendarICALView.as_view(),
        name="tree_calendar_ical",
    ),
    path(
        "<org_or_user_name>/<repo_name>/admin",
        views.GithubRepositoryAdminView.as_view(),
        name="admin",
    ),
]
