from django.urls import path

from . import views

app_name = "datatighubgit_repository"
urlpatterns = [
    path(
        "<repository_slug>",
        views.GitRepositoryView.as_view(),
        name="index",
    ),
    path(
        "<repository_slug>/builds",
        views.GitRepositoryBuildsView.as_view(),
        name="builds",
    ),
    path(
        "<repository_slug>/webhook/<webhook_code>",
        views.GitRepositorWebhookView.as_view(),
        name="webhook",
    ),
    path(
        "<repository_slug>/tree/<tree_name>",
        views.GitRepositoryTreeView.as_view(),
        name="tree_index",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/api1.json",
        views.GitRepositoryTreeAPI1View.as_view(),
        name="tree_api1",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/errors",
        views.GitRepositoryTreeErrorsView.as_view(),
        name="tree_errors_index",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/type/<type_id>",
        views.GitRepositoryTreeTypeView.as_view(),
        name="tree_type_index",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/type/<type_id>/record",
        views.GitRepositoryTreeTypeListRecordsView.as_view(),
        name="tree_type_list_records",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/type/<type_id>/record_api1.json",
        views.GitRepositoryTreeTypeListRecordsAPI1View.as_view(),
        name="tree_type_list_records_api1",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/type/<type_id>/api1.json",
        views.GitRepositoryTreeTypeAPI1View.as_view(),
        name="tree_type_api1",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/type/<type_id>/new_record",
        views.GitRepositoryTreeTypeNewRecordView.as_view(),
        name="tree_type_new_record",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/type/<type_id>/record/<record_id>",
        views.GitRepositoryTreeTypeRecordView.as_view(),
        name="tree_type_record_index",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/type/<type_id>/record/<record_id>/api1.json",
        views.GitRepositoryTreeTypeRecordAPI1View.as_view(),
        name="tree_type_record_api1",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/type/<type_id>/record/<record_id>/edit",
        views.GitRepositoryTreeTypeRecordEditView.as_view(),
        name="tree_type_record_edit",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/type/<type_id>/field/<field_id>",
        views.GitRepositoryTreeTypeFieldView.as_view(),
        name="tree_type_field_index",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/download/sqlite",
        views.GitRepositoryTreeDownloadSQLiteView.as_view(),
        name="tree_download_sqlite_index",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/download/frictionless_csv_zip",
        views.GitRepositoryTreeDownloadFrictionlessView.as_view(),
        name="tree_download_frictionless_index",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/calendar/<calendar_id>",
        views.GitRepositoryTreeCalendarView.as_view(),
        name="tree_calendar_index",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/calendar/<calendar_id>/api1.json",
        views.GitRepositoryTreeCalendarAPI1View.as_view(),
        name="tree_calendar_api1",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/calendar/<calendar_id>/fullcalendar.json",
        views.GitRepositoryTreeCalendarFullCalendarDataView.as_view(),
        name="tree_calendar_fullcalendar_data",
    ),
    path(
        "<repository_slug>/tree/<tree_name>/calendar/<calendar_id>/events.ical",
        views.GitRepositoryTreeCalendarICALView.as_view(),
        name="tree_calendar_ical",
    ),
    path(
        "<repository_slug>/admin",
        views.GitRepositoryAdminView.as_view(),
        name="admin",
    ),
]
