# Generated by Django 5.2.7 on 2026-01-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datatighubgit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitrepository",
            name="directory",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
