"""
Django settings for datatighub project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

import environ
import sentry_sdk

import datatighubgithub.settings

env = environ.Env(
    DATATIG_HUB_DATABASE_NAME=(str, "app"),
    DATATIG_HUB_DATABASE_USER=(str, "app"),
    DATATIG_HUB_DATABASE_PASSWORD=(str, "password"),
    DATATIG_HUB_DATABASE_HOST=(str, "localhost"),
    DATATIG_HUB_CELERY_BROKER_URL=(str, "localhost"),
    DATATIG_HUB_NAME=(str, "Dev Server"),
    DATATIG_HUB_EMAIL=(str, "test@example.com"),
    DATATIG_HUB_META_ROBOTS=(str, "noindex, nofollow"),
    DATATIG_HUB_DOMAIN=(str, "dev.hub.datatig.com"),
    DATATIG_HUB_HTTPS=(bool, False),
    DATATIG_HUB_DEBUG=(bool, False),
    DATATIG_HUB_SECRET_KEY=(
        str,
        "django-insecure-#s4^2+*_e%(r-htzm7-mu-@w&a4@2dma+c89!28%7-h1x#00_7",
    ),
    DATATIG_HUB_DATA_STORAGE_V1=(str, "/data/v1/"),
    DATATIG_HUB_STATIC_ROOT=(str, ""),
    DATATIG_HUB_SESSION_FILE_PATH=(str, None),
    DATATIG_HUB_SENTRY_DSN=(str, None),
    DATATIG_HUB_LINK_CHECKER_ENABLED=(bool, True),
    DATATIG_HUB_LINK_CHECKER_SECONDS_TILL_CHECK_URL_AGAIN=(int, 604800),  # 1 week
    DATATIG_HUB_LINK_CHECKER_SECONDS_TILL_CHECK_ROBOTS_TXT_AGAIN=(int, 86400),  # 1 day
    DATATIG_HUB_LINK_CHECKER_ROBOTS_TXT_CACHE_SIZE=(int, 10),
    DATATIG_HUB_LINK_CHECKER_USER_AGENT=(str, None),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DATATIG_HUB_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DATATIG_HUB_DEBUG")

ALLOWED_HOSTS = [env("DATATIG_HUB_DOMAIN")]


# Application definition

INSTALLED_APPS = [
    "datatighubcore.apps.DatatighubcoreConfig",
    "datatighubgithub.apps.DatatighubgithubConfig",
    "datatighubgit.apps.DatatighubgitConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "datatighub.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "datatighubcore.context_processors.datatig_hub_context_processor",
            ],
        },
    },
]

WSGI_APPLICATION = "datatighub.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DATATIG_HUB_DATABASE_NAME"),
        "USER": env("DATATIG_HUB_DATABASE_USER"),
        "PASSWORD": env("DATATIG_HUB_DATABASE_PASSWORD"),
        "HOST": env("DATATIG_HUB_DATABASE_HOST"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = env("DATATIG_HUB_STATIC_ROOT")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DATA_STORAGE_V1 = env("DATATIG_HUB_DATA_STORAGE_V1")

CELERY_BROKER_URL = env("DATATIG_HUB_CELERY_BROKER_URL")
if CELERY_BROKER_URL == "memory://":
    CELERY_TASK_ALWAYS_EAGER = True
CELERY_WORKER_CONCURRENCY = 1
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Disable this

DATATIG_HUB_NAME = env("DATATIG_HUB_NAME")
DATATIG_HUB_EMAIL = env("DATATIG_HUB_EMAIL")
DATATIG_HUB_META_ROBOTS = env("DATATIG_HUB_META_ROBOTS")
DATATIG_HUB_DOMAIN = env("DATATIG_HUB_DOMAIN")
DATATIG_HUB_HTTPS = env("DATATIG_HUB_HTTPS")

DATATIG_HUB_GITHUB = datatighubgithub.settings.SETTINGS

SESSION_ENGINE = "django.contrib.sessions.backends.file"
SESSION_FILE_PATH = env("DATATIG_HUB_SESSION_FILE_PATH")

DATATIG_HUB_LINK_CHECKER_ENABLED = env("DATATIG_HUB_LINK_CHECKER_ENABLED")
DATATIG_HUB_LINK_CHECKER_SECONDS_TILL_CHECK_URL_AGAIN = env("DATATIG_HUB_LINK_CHECKER_SECONDS_TILL_CHECK_URL_AGAIN")
DATATIG_HUB_LINK_CHECKER_SECONDS_TILL_CHECK_ROBOTS_TXT_AGAIN = env(
    "DATATIG_HUB_LINK_CHECKER_SECONDS_TILL_CHECK_ROBOTS_TXT_AGAIN"
)
DATATIG_HUB_LINK_CHECKER_ROBOTS_TXT_CACHE_SIZE = env("DATATIG_HUB_LINK_CHECKER_ROBOTS_TXT_CACHE_SIZE")
DATATIG_HUB_LINK_CHECKER_USER_AGENT = env("DATATIG_HUB_LINK_CHECKER_USER_AGENT") or DATATIG_HUB_NAME + " Link Checker"


if env("DATATIG_HUB_SENTRY_DSN"):
    sentry_sdk.init(
        dsn=env("DATATIG_HUB_SENTRY_DSN"),
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        traces_sample_rate=0.0,
        # Set profiles_sample_rate to 1.0 to profile 100%
        # of sampled transactions.
        # We recommend adjusting this value in production.
        profiles_sample_rate=0.0,
    )
