name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
        architecture: x64
    - run: pip install -r requirements_dev.txt
    - run: black --check *.py */
      working-directory: ./datatighub
    - run: isort --check-only *.py */
      working-directory: ./datatighub
    - run: flake8
      working-directory: ./datatighub
    - run: mypy --install-types --non-interactive .
      working-directory: ./datatighub

